project:
  type: website
  output-dir: _site
  preview:
    port: 4000
    timeout: 1200

website:

  title: Ford Johnson
  description: Data analyst turning raw data into insights, visualizations, and strategies that drive smarter business decisions.
  site-url: https://fordjohnson.dev
  favicon: https://cdn.jsdelivr.net/gh/bradfordjohnson/global-assets@master/images/logo/favicon.png
  image: https://cdn.jsdelivr.net/gh/bradfordjohnson/global-assets@master/images/logo/logo.png
  search: false

  open-graph:
    image: https://cdn.jsdelivr.net/gh/bradfordjohnson/global-assets@master/images/logo/logo.png

  navbar:
    background: white
    pinned: true
    logo: https://cdn.jsdelivr.net/gh/bradfordjohnson/global-assets@master/images/logo/logo.png
    left:
      - text: Home
        href: index.qmd
      - text: About
        href: about/index.qmd
      - text: Data
        href: data/index.qmd
    right:
      - icon: github
        href: https://github.com/bradfordjohnson
      - icon: linkedin
        href: https://linkedin.com/in/bradford-ford-johnson

  page-footer:
    center:
      - icon: github
        href: https://github.com/bradfordjohnson
      - icon: linkedin
        href: https://linkedin.com/in/bradford-ford-johnson


format:
  html:
    page-layout: full
    theme: styles.scss
    
    toc: false
    anchor-sections: false
    canonical-url: true
    lang: en
    smooth-scroll: true

    include-in-header: ga4/gtm_header.html
    include-before-body: ga4/gtm_body.html

    lightbox:
      match: auto
      effect: zoom
