project:
  type: website
  output-dir: docs

website:
  title: "Ford Johnson"
  favicon: images/favicon.png
  bread-crumbs: true
  navbar:
    right:
      - href: index.qmd
        text: Home
  page-footer:
    left: Copyright &copy; 2024 Ford Johnson
    center:
      - icon: linkedin
        href: https://linkedin.com/in/bradford-ford-johnson
      - icon: github
        href: https://github.com/bradfordjohnson

format:
  html:
    theme: cosmo
    anchor-sections: false
    css: styles.css
    toc: false



