project:
  type: website
  output-dir: docs

website:
  title: "Ford Johnson"
  favicon: images/favicon.png
  site-url: https://fordjohnson.dev
  open-graph: true
  search: false
  bread-crumbs: true
  navbar:
    pinned: true
    right:
      - href: portfolio/index.qmd
        text: Portfolio
      - href: gallery/index.qmd
        text: Gallery
      - href: notes/index.qmd
        text: Notes
      - href: about/index.qmd
        text: About
      - href: https://github.com/bradfordjohnson
        icon: github
      - href: https://linkedin.com/in/bradford-ford-johnson
        icon: linkedin
  page-footer:
    left: Copyright &copy; 2024 Ford Johnson
    center:
      - icon: github
        href: https://github.com/bradfordjohnson
      - icon: linkedin
        href: https://linkedin.com/in/bradford-ford-johnson
format:
  html:
    anchor-sections: false
    theme: styles.scss
    toc: false
    canonical-url: true
