project:
  type: website
  output-dir: docs

website:
  title: Ford Johnson
  site-url: https://fordjohnson.dev
  favicon: images/favicon.png
  image: images/logo.png
  search: false

  open-graph:
    image: images/logo.png

  announcement:
    type: warning
    position: below-navbar 
    content: "Site updates are in progress :)"
    icon: wrench

  navbar:
    pinned: true
    logo: images/logo.png

    right:
      - icon: github
        href: https://github.com/bradfordjohnson
      - icon: linkedin
        href: https://linkedin.com/in/bradford-ford-johnson

  page-footer:
    center:
      - icon: github
        href: https://github.com/bradfordjohnson
      - icon: linkedin
        href: https://linkedin.com/in/bradford-ford-johnson

format:
  html:
    page-layout: full
    include-in-header: ga4/gtm_header.html
    include-before-body: ga4/gtm_body.html

    theme: styles.scss,
    css: styles.css
    toc: false
    anchor-sections: true
    canonical-url: true
    lang: en

    lightbox:
      match: auto
      effect: zoom

# build via:
# quarto preview --render all --no-watch-inputs