---
metadata-files: 
  - _meta.yml
---

{{< include ../_components/hero-split.qmd >}}

::: {.content-block}
::: {.features}

::: {.feature}
### Visualizing data for impact
Transforming raw data into understandable and actionable visuals. My expertise includes creating interactive dashboards and static graphics using tools such as Tableau, Looker, and R (with ggplot2), ensuring clarity and effective communication of key findings.

<!-- ::: {.learn-more}
[Learn more »](/../)
::: -->
:::

::: {.feature}
### Driving growth with web data
Utilizing web analytics tools such as Google Analytics to monitor user engagement, analyze traffic sources, and measure the success of marketing initiatives. I focus on providing data-driven recommendations for website optimization and improved marketing ROI.
:::

::: {.feature}
### Cloud data infrastructure
Experienced in developing and deploying scalable data pipelines and analytical environments on cloud platforms, particularly Google Cloud Platform (GCP). I leverage services like BigQuery, Cloud Storage, and Dataform for robust data processing and insight generation.

:::

:::
:::

::: {.content-block}


{{< include ../_components/network-visual.qmd >}}

### Beyond Data
When I’m not working with data, I’m probably out hiking, trying to capture the perfect shot with my camera, or learning to golf. I love exploring the world and finding new perspectives, whether it’s through travel, photography, or just enjoying the great outdoors.

:::